name: CMake on multiple platforms

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        build_type: [Release]
        c_compiler: [gcc, clang, cl]
        include:
          - os: windows-latest
            c_compiler: cl
            cpp_compiler: cl
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
          - os: ubuntu-latest
            c_compiler: clang
            cpp_compiler: clang++

    steps:
      - name: Check out code
        uses: actions/checkout@v2
        
      - name: Install SDL2
        run: sudo apt install libsdl2-dev

      - name: Install SDL2-Mixer
        run: sudo apt install libsdl2-mixer-dev

      - name: Install SDL2-Image
        run: sudo apt install libsdl2-image-dev

      - name: Configure CMake
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release
      - name: Build
        run: |
          cd build
          cmake --build .

      - name: Test
        working-directory: build
        run: ctest --build-config ${{ matrix.build_type }}
